### ISSUE TITLE
[NOT ISSUE] - Thanks!

### ISSUE THREAD

**Issue by dotbear** [Atreyyo/KTMod#1]
Hey mate, I know I'm abusing the github issue system a bit here but I just wanted to chime in and thank you for your work. Love your addons!

As a software engineer myself I've been reading through your code (especially the IWin stuff). I'm interested in making some of my own - are you selftaught by trial and error or where do you find your resources for learning the vanilla wow addon codebase?

**Comment by Atreyyo** [comment]
> Hey mate, I know I'm abusing the github issue system a bit here but I just wanted to chime in and thank you for your work. Love your addons!
> 
> As a software engineer myself I've been reading through your code (especially the IWin stuff). I'm interested in making some of my own - are you selftaught by trial and error or where do you find your resources for learning the vanilla wow addon codebase?

Hey there, glad to see you like my stuff!
I'm pretty much selftaught by trial and error like you said.
When I first started out trying to learn lua, what really helped me out a lot was looking at the code from other addons trying to see which functions and api's was being used aswell as trying to see the basic code structure of an addon.
I used Wowprogramming.com a lot to search for api's, even though I couldnt find everything I needed at times it still was very helpfull.

**Comment by dotbear** [comment]
Thanks a lot! :)
